In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


*This is installed in c drive (global)
*we will create our own vrtual enviornment (to save space)
*kuch libraries c drive m nhi chlti


In [2]:
import os
import numpy as np

In [3]:
print("hello")

hello


In [4]:
import numpy as np

In [5]:
import numpy as np

## NumPy in Python

NumPy (Numerical Python) is a powerful Python library used for numerical and mathematical operations. It provides support for arrays, matrices, and many built-in functions for fast calculations. NumPy is faster and more memory-efficient than normal Python lists.

### Features

* Supports N-dimensional arrays
* Performs mathematical operations easily
* Useful for matrix and statistical calculations
* Faster data processing

### Uses

NumPy is widely used in Data Science, Machine Learning, and Data Analytics. It also works with libraries like Pandas and Matplotlib.


In [6]:
np.__version__

'2.4.6'

In [7]:
lst = list (range(1,20))

In [8]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [9]:
arr = np.array(lst)

In [10]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:
lst = [1,2,3,4,7,8,9]
arr = np.array(lst)

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr = np.array([1,21,2,4,7,8,9,9,8,7,3,2])

In [14]:
arr = np.array([range(1,20)])

In [15]:
type(arr)

numpy.ndarray

In [16]:
arr = np.arange(1,21)

In [17]:
type(arr)

numpy.ndarray

In [18]:
arr = np.zeros(10)#array of 0s

In [19]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
arr = np.ones(10)#array of 1s

In [21]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
arr = np.zeros((7,10))# 2d array
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
arr = np.zeros((7,10))### ndim is used to show the dimensions of the array
print(arr.ndim)

2


In [24]:
arr = np.linspace(1,10,7)# total 7 elements print hongi all between 1 to 10
print(arr)
print(type(arr))

[ 1.   2.5  4.   5.5  7.   8.5 10. ]
<class 'numpy.ndarray'>


In [25]:
arr = np.arange(0,30)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
#np.reshape()
arr = arr.reshape(10,3)#converted from 1d to 2d array

In [28]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [29]:
arr = arr.reshape(5,6)

In [30]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
arr = np.random.randint(1,5,(5,6))
arr


array([[4, 1, 3, 4, 4, 2],
       [2, 3, 3, 4, 2, 2],
       [4, 1, 4, 4, 4, 4],
       [3, 4, 3, 3, 3, 1],
       [2, 3, 2, 1, 3, 4]], dtype=int32)

In [32]:
np.random.random(10)

array([0.50062061, 0.41181526, 0.20263862, 0.55353423, 0.0084313 ,
       0.86685323, 0.64246303, 0.03100817, 0.52004639, 0.73614366])

In [33]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [34]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)


2
(12, 5)
int64
60


In [35]:
lst = [[1,2,3],[7,8,9]]
lst

[[1, 2, 3], [7, 8, 9]]

In [36]:
arr = np.array(lst)


In [37]:
arr

array([[1, 2, 3],
       [7, 8, 9]])

In [38]:
arr = np.arange(60).reshape(12,5)



In [39]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [40]:
print(arr.shape)

(12, 5)


In [41]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [42]:
# 5

In [43]:
# 6

In [44]:
arr[0,0]

np.int64(0)

In [45]:
arr[0][0]


np.int64(0)

In [46]:
arr[11,4]

np.int64(59)

In [47]:
arr[-1,-1]

np.int64(59)

In [48]:
arr[11,-1]

np.int64(59)

In [49]:
arr[-1,4]

np.int64(59)

In [50]:
arr[2:4]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [51]:
arr[2:4,3:]

array([[13, 14],
       [18, 19]])

In [52]:
arr[0:9,3:4]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28],
       [33],
       [38],
       [43]])

In [53]:
arr[-1,-1]=100

In [54]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58, 100]])

In [55]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

2
(12, 5)
int64
60


3D ARRAY

In [56]:
arr = np.arange(225).reshape(5,15,3)# 5 is for table #15 denotes columns # 3 denotes no. of elements in row

In [57]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [58]:
arr[0][0]

array([0, 1, 2])

In [59]:
arr[0][0][0]

np.int64(0)

In [60]:
arr[-1]#last table

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [61]:
#each table 1st row
arr[0:5,0]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [62]:
arr[0:5,0,0]#each tables's 1st element

array([  0,  45,  90, 135, 180])

In [63]:
arr[0:5,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [64]:
#3rd and 4th row of each table
arr[0:5,2:4]


array([[[  6,   7,   8],
        [  9,  10,  11]],

       [[ 51,  52,  53],
        [ 54,  55,  56]],

       [[ 96,  97,  98],
        [ 99, 100, 101]],

       [[141, 142, 143],
        [144, 145, 146]],

       [[186, 187, 188],
        [189, 190, 191]]])

In [65]:
#each table's 3rd and 4th column
arr[0:5,0:3,2:4]

array([[[  2],
        [  5],
        [  8]],

       [[ 47],
        [ 50],
        [ 53]],

       [[ 92],
        [ 95],
        [ 98]],

       [[137],
        [140],
        [143]],

       [[182],
        [185],
        [188]]])

In [66]:
#each table's last element
arr[0:5,-1,-1]

array([ 44,  89, 134, 179, 224])

In [67]:
arr[0:5,14,2]

array([ 44,  89, 134, 179, 224])

In [68]:
arr[0:5,-1,2]

array([ 44,  89, 134, 179, 224])

In [69]:
arr[0:5,14,-1]

array([ 44,  89, 134, 179, 224])

In [70]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

3
(5, 15, 3)
int64
225


In [71]:
#replacing a particular element
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [72]:
#operations on array
# arr1 = np.

In [73]:
# ==============================
# NumPy Array Operations Example
# ==============================

import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

print("\n========== OPERATIONS ==========\n")

# Multiplication
print("1️⃣ Multiplication (*)")
print("arr1 * arr2 =", arr1 * arr2)

# Division
print("\n2️⃣ Division (/)")
print("arr1 / arr2 =", arr1 / arr2)

# Addition
print("\n3️⃣ Addition (+)")
print("arr1 + arr2 =", arr1 + arr2)

# Subtraction
print("\n4️⃣ Subtraction (-)")
print("arr1 - arr2 =", arr1 - arr2)

# Positive Sign with Multiplication
print("\n5️⃣ Multiplication with Unary Plus (* +)")
print("arr1 * +arr2 =", arr1 * +arr2)

# Floor Division
print("\n6️⃣ Floor Division (//)")
print("arr1 // +arr2 =", arr1 // +arr2)

print("\n✅ All operations completed successfully!")

Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]

========== OPERATIONS ==========

1️⃣ Multiplication (*)
arr1 * arr2 = [ 20  80 180 320]

2️⃣ Division (/)
arr1 / arr2 = [5. 5. 5. 5.]

3️⃣ Addition (+)
arr1 + arr2 = [12 24 36 48]

4️⃣ Subtraction (-)
arr1 - arr2 = [ 8 16 24 32]

5️⃣ Multiplication with Unary Plus (* +)
arr1 * +arr2 = [ 20  80 180 320]

6️⃣ Floor Division (//)
arr1 // +arr2 = [5 5 5 5]

✅ All operations completed successfully!


In [74]:
#sorting in array
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)


Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]


In [75]:
arr1.sort()

In [76]:
arr1

array([10, 20, 30, 40])

In [77]:
arr2 =np.array([2,8,9,7,4,3,])

In [78]:
arr2.sort()

In [79]:
arr2

array([2, 3, 4, 7, 8, 9])

In [80]:
arr =np.arange(225)

In [81]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [82]:
arr = arr.reshape(5,15,3)

In [83]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11